### ISSUE TITLE
Running any DB interaction command with `""` errors

### ISSUE THREAD

**Issue by MultisampledNight** [mgax/minivirt#7]
Running

```
 $ miv run ""
```

results in

```python
Traceback (most recent call last):
  File "/home/multisn8/.local/bin/miv", line 8, in <module>
    sys.exit(cli())
  File "/home/multisn8/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/multisn8/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/multisn8/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/multisn8/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/multisn8/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/multisn8/.local/lib/python3.10/site-packages/minivirt/cli.py", line 145, in run
    image = db.get_image(image_name)
  File "/home/multisn8/.local/lib/python3.10/site-packages/minivirt/db.py", line 168, in get_image
    return Image(self, name)
  File "/home/multisn8/.local/lib/python3.10/site-packages/minivirt/db.py", line 27, in __init__
    assert re.match(r'^[0-9a-f]{64}$', name)
AssertionError
```

It'd probably be best to not to bail out early if commands are run with empty arguments.

**Comment by mgax** [comment]
The error comes from a lazy check:
1. Is this reference a tag? No, so let's assume it's an image ID.
2. Does that path exist? It does! Never mind that it's the images directory and not an image within: https://github.com/mgax/minivirt/blob/2e6e5f47a0d1a674bbb0ac4bef1b5112614e77f0/minivirt/db.py#L166
3. Does it look like a valid image ID? No, bail.

The code should throw an `ImageNotFound` exception, something the CLI layer will understand and report properly.
